# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177634c7a196568420a151e65331fb91384d21d8de68712aa68402126b1e3e4e2342793e2ae9e59ddeada21fa1f10accd5df85d96bc3272d7e8536853b69437c

test:
  secret_key_base: e45f9cab58be3772a290c13b56437249d21ddf97af4621bb1ede685b98a65fb0e18b7198fd1d2f409fcb1e15159652a59af2603e816fd82df0232f4a5064e7e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
